### ISSUE TITLE
Change title to "Firefox Quantum Extensions Challenge." 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extensions-challenge#1]
Per legal, we need to rename this contest "Firefox Quantum Extensions Challenge." 
![screen shot 2018-03-05 at 9 18 21 am](https://user-images.githubusercontent.com/23342476/36989303-2cd66a8c-2056-11e8-893c-69b1d66ec355.png)

**Comment by slightlyoffbeat** [comment]
Fixed here: dfa18ba80dcc42e97e7eddde5c2eb0646dbe8738
