### ISSUE TITLE
Analytics isn't configured

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extensions-challenge#11]
We need a new property and GA id to be setup.

**Comment by muffinresearch** [comment]
@caitmuenster do you know if anyone has requested this being setup yet?

**Comment by caitmuenster** [comment]
@muffinresearch It has and I just cc'd you on [bug 1442317](https://bugzilla.mozilla.org/show_bug.cgi?id=1442317) to loop you in.

**Comment by muffinresearch** [comment]
> @muffinresearch It has and I just cc'd you on bug 1442317 to loop you in.

@caitmuenster thanks - I'll get that added + deployed tomorrow.

**Comment by muffinresearch** [comment]
Fixed and released as part of release 0.0.7
