### ISSUE TITLE
AccessDenied for deletions during deploy.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extensions-challenge#12]
Seeing a lot of the following messages during the deployment: 

```
An error occurred (AccessDenied) when calling the DeleteObject operation: Access Denied
```

@bqbn I'm not sure if this means the bucket is filling up if the script can't delete things?

**Comment by bqbn** [comment]
This was due to the IAM user lacking of the permission to delete S3 objects. It has been fixed.
