### ISSUE TITLE
Fix type in twitter:title meta

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extensions-challenge#14]
The social team noticed during campaign set up that this shows up as FireFox in the twitter:title meta. Can we update to Firefox? 

Cc @hondurasjones

**Comment by muffinresearch** [comment]
Fixed in https://github.com/mozilla/extensions-challenge/commit/59df9304c60d4bd144b8cc4458404f946434aba6

**Comment by muffinresearch** [comment]
Will be released in a few minutes...
