### ISSUE TITLE
Add WeTransfer logo and new text to "Prizes" section

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extensions-challenge#16]
WeTransfer has come onboard as a sponsor for the Firefox Quantum Extensions Challenge and will be offering a 1-year WT Plus account to anyone who submits an extension to the contest (value of $120/year). 

@slightlyoffbeat / @muffinresearch, can we add their logo and a bit of text under the two prizes in the Prizes section? 

Logo: https://wetransfer.pr.co/presskit/217754 (Weplaatje.png)

Text: All entrants with valid submissions will receive one free year of [WeTransfer Plus](https://wetransfer.com/about).  

Timing: ASAP

**Comment by muffinresearch** [comment]
Fixed and released.
![screen shot 2018-04-06 at 13 16 58](https://user-images.githubusercontent.com/1514/38420793-e08e9b30-399c-11e8-90a9-9ade97cb8d61.png)
![screen shot 2018-04-06 at 13 16 49](https://user-images.githubusercontent.com/1514/38420795-e0ad017e-399c-11e8-86e6-a824f49fee53.png)
![screen shot 2018-04-06 at 13 17 06](https://user-images.githubusercontent.com/1514/38420792-e07595d6-399c-11e8-854a-e38dbdaad878.png)
