### ISSUE TITLE
Update contest name to "Firefox Quantum Extensions Challenge" on Rules page

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extensions-challenge#2]
There are two instances: 

1) The title at the top of the page

![screen shot 2018-03-05 at 9 21 04 am](https://user-images.githubusercontent.com/23342476/36989422-8d8c204c-2056-11e8-8f61-c2a063620aa3.png)

2) On part 15, which should read, "Mozilla Firefox Quantum Extensions Challenge..."

![screen shot 2018-03-05 at 9 21 48 am](https://user-images.githubusercontent.com/23342476/36989449-a4f3f2aa-2056-11e8-814f-a2044c7dcdb8.png)

**Comment by slightlyoffbeat** [comment]
Fixed here: dfa18ba80dcc42e97e7eddde5c2eb0646dbe8738
