### ISSUE TITLE
Headers are prefixed

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extensions-challenge#7]
Headers in responses seem to be passed with a `x-amz-meta` prefix - these need to be set to send the original header in a response so that the client sees them.

Here's a screenshot:

<img width="555" alt="quantum_extensions_challenge" src="https://user-images.githubusercontent.com/1514/37088313-ce2199f8-21f4-11e8-9ba8-3e045372967a.png">

**Comment by muffinresearch** [comment]
I think this might be something that needs to be configured on AWS.

**Comment by bqbn** [comment]
According to the [document](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-metadata), AWS will add `x-amz-meta-` prefix to user defined meta data. The best part is there is no way you can disable that.

Then an [edge lambda](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html) has to be used to get rid of them before the headers are saved in cloudfront.
