### ISSUE TITLE
Add hot links

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extensions-challenge#8]
Would be great to add hot links for the Prizes and Judging sections -- the hot links will be used in the announcement email.

**Comment by muffinresearch** [comment]
@caitmuenster does this mean you need links in the main navigation for the judges and prizes sections? Or just the ability to link via a fragment id? E.g: `#judges`

**Comment by muffinresearch** [comment]
@caitmuenster I've added scrollable wrappers so that /#judges and /#prizes can be linked to. 

If that's all you need this can be closed, if you need those links added to the nav let me know, it's a simple fix.

**Comment by caitmuenster** [comment]
That's perfect, @muffinresearch! Thanks so much.

**Comment by caitmuenster** [comment]
Sorry, @muffinresearch -- I just tried extensionschallenge.com/#prizes and extensionschallenge.com/#judges and wasn't taken to those sections. Is this user error on my part?

**Comment by muffinresearch** [comment]
> Sorry, @muffinresearch -- I just tried extensionschallenge.com/#prizes and extensionschallenge.com/#judges and wasn't taken to those sections. Is this user error on my part?

Hmm - it should work - it's definitely working for me. I wonder if you're seeing a cached version of the content for some reason. That shouldn't happen since the HTML should be only cached for a limited time and subsequently the JS should be updated since the URLS referencing it should have changed.

**Comment by caitmuenster** [comment]
Definitely weird. I updated Firefox and had the same problem, but it worked for me when I tested it in Chrome. 

I'm doing a quick survey of the ACE team to see what they experience. If it's just me, we can close this.

**Comment by muffinresearch** [comment]
@caitmuenster definitely sounds like caching. 

One thing that might confirm that is if you can see the tracking happening now that Analytics is enabled and was released my AM today.

**Comment by caitmuenster** [comment]
I'm good with closing if this will fix itself. :)
