### ISSUE TITLE
Submit button links to a CSS-less Google form 

### ISSUE THREAD

**Issue by atsay** [mozilla/extensions-challenge#9]
I visited https://extensionschallenge.com/ for the first time today, and when I clicked on the Submit links, I was taken to a Google submission form that had no CSS: https://www.dropbox.com/s/5nt400ykw00fxdd/Screenshot%202018-03-07%2011.31.13.png?dl=0

I noticed the URL, https://docs.google.com/forms/d/e/1FAIpQLSee12qcrY1o1QSQUHvSBdwOEoICd9jRuimWvmt1zKWPoJhdXA/viewform?usp=send_form, had an extra "?usp=send_form" at the end. Removing it made the CSS come back.

**Comment by muffinresearch** [comment]
FWIW - I don't see this issue.

**Comment by muffinresearch** [comment]
@atsay can you see if you can still reproduce it. Maybe it was something intermittent happening on Google forms?

**Comment by atsay** [comment]
I can't reproduce it anymore :-/ only happened the first time.

**Comment by muffinresearch** [comment]
@atsay ok thanks, on that basis I'm going to close this - please reopen if it happens again.
